[common]
compressAnywhere = false
compressBlacklist = ["minecraft:sandstone", "minecraft:iron_trapdoor"]
[client]
hideButtons = true
rightClickCraftsStack = true
hideButtonTooltips = false
hideVanillaCraftingGuide = true
craftingTweaksMode = "DEFAULT"
disabledAddons = []
