
# Configuration for async io system
[asyncIO]
	# (Default: 4) Serializer executor parallelism
	ioWorkerParallelism = 4
	# (Default: 2) IO worker executor parallelism
	serializerParallelism = 2

# Configuration for threaded world generation
[threadedWorldGen]
	# (Default: false) Whether to allow feature generation (world decorations like trees, ores and etc.) run in parallel
	allowThreadedFeatures = false
	# (Default: 4) World generation worker executor parallelism
	parallelism = 4
	# (Default: true) Whether to enable this feature
	enabled = true

